# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('char_class', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=50)),
                ('alignment', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('acrobatics', models.IntegerField()),
                ('animal_handling', models.IntegerField()),
                ('arcana', models.IntegerField()),
                ('athletics', models.IntegerField()),
                ('deception', models.IntegerField()),
                ('history', models.IntegerField()),
                ('insight', models.IntegerField()),
                ('intimidation', models.IntegerField()),
                ('investigation', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('nature', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('persuasion', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('sleight_of_hand', models.IntegerField()),
                ('stealth', models.IntegerField()),
                ('survival', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('personality', models.IntegerField()),
                ('ideals', models.IntegerField()),
                ('bonds', models.IntegerField()),
                ('flaws', models.IntegerField()),
            ],
        ),
    ]
