# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
    ]
