# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0002_characterfeatures_equipment_languages_traits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='spells',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character'),
        ),
    ]
