# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0004_auto_20170528_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
