# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0006_auto_20170528_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='bonds',
            field=models.CharField(default='nill', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='flaws',
            field=models.CharField(default='nill', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='ideals',
            field=models.CharField(default='nill', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(default='nill', max_length=250),
            preserve_default=False,
        ),
    ]
