# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0008_auto_20170531_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterfeatures',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
