# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0009_auto_20170531_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='spells',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='traits',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
