# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0010_auto_20170531_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
