# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0013_auto_20170604_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
