# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0014_auto_20170604_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccreator.Character')),
            ],
        ),
        migrations.RemoveField(
            model_name='characterfeatures',
            name='character',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='character',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='character',
        ),
        migrations.RemoveField(
            model_name='traits',
            name='character',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.CharField(default='nill', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterFeatures',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.DeleteModel(
            name='Spells',
        ),
        migrations.DeleteModel(
            name='Traits',
        ),
    ]
