# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0021_auto_20170608_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='user_id',
            new_name='user',
        ),
    ]
