# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccreator', '0022_auto_20170608_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
